# .air.toml

# 设置项目根目录
root = "."

# [build] 部分用于定义编译命令和其他编译选项
[build]
  # 修改编译命令，使用相对路径
  cmd = "go build -o tmp/main.exe cmd/main.go"
  # 指定生成的可执行文件
  bin = "tmp/main.exe"
  # 设置工作目录
  full_bin = "tmp/main.exe"
  # 监视的文件类型
  include_ext = ["go", "yaml"]
  # 排除的目录
  exclude_dir = ["tmp", "vendor"]
  # 监视的文件变化
  include_file = []
  # 排除的文件
  exclude_file = []
  # 延迟时间
  delay = 1000
  # 终止超时时间
  kill_delay = "0.5s"
  # 是否发送中断信号
  send_interrupt = false
  # 是否在启动时清理旧的构建文件
  clean_on_exit = false

[run]
  # 设置运行命令
  cmd = "./tmp/main.exe"

# [color] 部分用于定义输出颜色
[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

# [log] 部分用于定义日志设置
[log]
  time = false

# [misc] 部分用于定义其他设置
[misc]
  clean_on_exit = false

# [screen] 部分用于定义清屏设置
[screen]
  clear_on_rebuild = false
