name: Deploy fangkongxinsheng-go 🚀

on:
  workflow_dispatch:

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the application
        run: go build -o myapp.exe ./cmd/main.go

      - name: Deploy to server
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key myapp.exe $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
          ssh -o StrictHostKeyChecking=no -i private_key -T $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
            echo "Checking if the file exists:"
            ls -l ${DEPLOY_PATH}myapp.exe
            echo "Starting or restarting the application using pm2:"
            pm2 start ${DEPLOY_PATH}myapp.exe --name fangkongxinsheng_server --watch --update-env || pm2 restart fangkongxinsheng_server --update-env
          EOF